### ISSUE TITLE
Error while running Attribute Value Grouping module

### ISSUE THREAD

**Issue by vijayendra-g** [xinyangz/OAMine#4]
Hi
While running Attribute Value Grouping module I keep getting following error

RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1695392020201/work/c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch

My current setting python3.10+cuda 12+torch2.3

Could you please let me know other details 
1. torch version
2. cuda version 
3. python version 

I also  tried   python3.6+cuda 12+torch1.7.1 with no success

**Comment by xinyangz** [comment]
Hi, the pytorch version was 1.8.1. Cuda was probably either 10.2 or 11.3.

**Comment by vijayendra-g** [comment]
@xinyangz  Thank you very much for quick response.
